from pydantic import BaseSettings, Field

class Settings(BaseSettings):
    access_token: str = 'EABWajZCu7kGoBAMhFxiOoyUEUVk5JgNagqkTF24rHZCD8k7ma7pOZCj7VdpEUZCbdjPpi1yLIU73GCZCJPOTwzaeZBrEy5TZC7dwTNvqRZCCMsAeRP1MfEolOtE42IA9TZBHmtBRFEZCbR09FbZCeWoclkNv6TGghK1a9nsyEfUDZCvSOSTySeSEtaUCYifRRxolRPKXJeBVVbTJk746LUPuHSSx'
