from pydantic import BaseSettings, Field

class Settings(BaseSettings):
    access_token: str = 'EABWajZCu7kGoBAMSpdQwTI2dnIqZCbGZArCLvZCNNjBUiMZBb5hqJKkHKw9tgjX1WFhSAUBKPvi6zZBYcinYM3GZAHt3Fb4haLuFuFpdzZCRyUVTDkpUqNn4HarbdKvnlkIFoRhRAdpwVp4mt3b2s17ZBfcT5kRP1LVojlh2Ib6t8SC8wUDZA5WzksMJedC4z44ATNIaobDsjz1FQuiJPWF9Ig'
